name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: pravinraj-ai
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker compose build
          docker images

                  
          docker tag three-tier-docker-mysql ghcr.io/pravinraj-ai/temp-pravin/three-tier-docker-mysql:latest
          docker tag three-tier-docker-app ghcr.io/pravinraj-ai/temp-pravin/three-tier-docker-app:latest
          docker tag three-tier-docker-web ghcr.io/pravinraj-ai/temp-pravin/three-tier-docker-web:latest
          
          docker push ghcr.io/pravinraj-ai/temp-pravin/three-tier-docker-mysql:latest
          docker push ghcr.io/pravinraj-ai/temp-pravin/three-tier-docker-app:latest
          docker push ghcr.io/pravinraj-ai/temp-pravin/three-tier-docker-web:latest
